export const QUESTIONS = [
  {
    id: 'name', type: 'text',
    eyebrow: "Let's start simple.",
    question: 'What should I call you?',
    placeholder: 'Your first name',
    key: 'userName', required: true,
  },
  {
    id: 'timing', type: 'cards',
    eyebrow: 'Take your time.',
    question: 'When did things end?',
    options: ['This week', 'This month', 'A few months ago', 'Over 6 months ago'],
    key: 'timeSinceBreakup', required: true,
  },
  {
    id: 'length', type: 'cards',
    eyebrow: 'I want to understand.',
    question: 'How long were you together?',
    options: ['Less than 6 months', '6-12 months', '1-2 years', '3-5 years', '5+ years'],
    key: 'relationshipLength', required: true,
  },
  {
    id: 'who', type: 'cards',
    eyebrow: 'No judgment here.',
    question: 'What happened between you two?',
    options: ['They ended it', 'I ended it', 'It was mutual', 'Its complicated'],
    key: 'breakupInitiator', required: true,
  },
  {
    id: 'feelings', type: 'chips',
    eyebrow: 'All of it is valid.',
    question: 'How are you feeling right now?',
    subtitle: 'Select everything that feels true',
    options: ['Heartbroken', 'Angry', 'Numb', 'Confused', 'Lost', 'Anxious', 'Relieved', 'Hopeful', 'Empty', 'Overwhelmed'],
    key: 'currentFeelings', required: true, multi: true,
  },
  {
    id: 'attachment1', type: 'cards', multi: true, maxSelect: 2,
    eyebrow: 'Understanding you better.',
    question: 'In relationships, which feels most true for you?',
    subtitle: 'Pick up to 2 that resonate',
    options: [
      'I worry my partner will lose interest or leave',
      'I find it hard to fully trust or depend on someone',
      'I felt secure and comfortable being close',
      'I wanted closeness but also felt overwhelmed by it',
    ],
    key: 'attachmentQ1', required: false,
  },
  {
    id: 'attachment2', type: 'cards', multi: true, maxSelect: 2,
    eyebrow: 'Still with you.',
    question: 'Since the breakup, what is your biggest fear?',
    subtitle: 'Pick up to 2 that feel true',
    options: [
      'Being alone and never finding love again',
      'Getting hurt if I open up to someone new',
      'Losing my sense of independence',
      'Not knowing what I actually want',
    ],
    key: 'attachmentQ2', required: false,
  },
  {
    id: 'attachment3', type: 'cards', multi: true, maxSelect: 2,
    eyebrow: 'Almost there.',
    question: 'When things got difficult between you, what did you tend to do?',
    subtitle: 'Pick up to 2 that sound like you',
    options: [
      'Seek reassurance and try to fix things immediately',
      'Pull back and need space to process',
      'Talk it through calmly when ready',
      'Swing between wanting to fix it and shutting down',
    ],
    key: 'attachmentQ3', required: false,
  },
  {
    id: 'goal', type: 'cards',
    eyebrow: "There's no wrong answer.",
    question: 'What brings you to Over It?',
    options: ['I need someone to talk to', 'I want to understand what happened', 'I want to heal and move forward', 'I am not sure yet'],
    key: 'primaryGoal', required: false,
  },
  {
    id: 'share', type: 'textarea',
    eyebrow: "You're almost in.",
    question: 'Anything you want me to know right away?',
    subtitle: 'Completely optional - skip ahead whenever you are ready',
    placeholder: 'Share whatever feels right...',
    key: 'initialShare', required: false,
  },
];
